//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HL7Parser
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataTypeColumn
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> DataTypeId { get; set; }
        public Nullable<long> Length { get; set; }
        public Nullable<long> Sequence { get; set; }
        public Nullable<bool> IsOptional { get; set; }
        public string DataType { get; set; }
    
        public virtual DataType DataType1 { get; set; }
    }
}
