//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HL7Parser
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventType
    {
        public long EventTypeId { get; set; }
        public string EventType1 { get; set; }
        public long MessageTypeId { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual MessageType MessageType { get; set; }
    }
}
