//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HL7Parser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segment
    {
        public string SegmentId { get; set; }
        public long Sequence { get; set; }
        public long Length { get; set; }
        public string Version { get; set; }
        public string Name { get; set; }
        public bool IsRequired { get; set; }
        public bool IsRepeating { get; set; }
    }
}
