//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HL7Parser
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegmentConfiguration
    {
        public long Id { get; set; }
        public string Version { get; set; }
        public string Segments { get; set; }
    }
}
