//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HL7Parser
{
    using System;
    using System.Collections.Generic;
    
    public partial class TriggerEvent
    {
        public string MessageType { get; set; }
        public string EventType { get; set; }
        public string Segment { get; set; }
        public bool IsOptional { get; set; }
        public bool IsRepeated { get; set; }
        public long Sequence { get; set; }
        public string Version { get; set; }
    }
}
