//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIParseConsole.Hl7API {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Hl7API.IHL7ParserService")]
    public interface IHL7ParserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHL7ParserService/ParseString", ReplyAction="http://tempuri.org/IHL7ParserService/ParseStringResponse")]
        HL7Parser.Models.HL7Message ParseString(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHL7ParserService/ParseString", ReplyAction="http://tempuri.org/IHL7ParserService/ParseStringResponse")]
        System.Threading.Tasks.Task<HL7Parser.Models.HL7Message> ParseStringAsync(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHL7ParserServiceChannel : EDIParseConsole.Hl7API.IHL7ParserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HL7ParserServiceClient : System.ServiceModel.ClientBase<EDIParseConsole.Hl7API.IHL7ParserService>, EDIParseConsole.Hl7API.IHL7ParserService {
        
        public HL7ParserServiceClient() {
        }
        
        public HL7ParserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HL7ParserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HL7ParserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HL7ParserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HL7Parser.Models.HL7Message ParseString(string message) {
            return base.Channel.ParseString(message);
        }
        
        public System.Threading.Tasks.Task<HL7Parser.Models.HL7Message> ParseStringAsync(string message) {
            return base.Channel.ParseStringAsync(message);
        }
    }
}
